[pytest]
addopts = -v -s
testpaths = tests
python_files = test_*.py
markers =
    smoke: Critical smoke tests
    regression: Full regression suite
    E2E: End-to-End scenarios
    login:Login related tests
    logout: Logout related tests
    leave: Leave related tests
    api: API tests
    slow: Long running tests

